kind: ConfigMap
apiVersion: v1
metadata:
  name: bigip-snatpool
  namespace: kube-system
  labels:
    f5type: virtual-server
    overrideAS3: "true"
data:
  template: |
   {
      "declaration": {
            "tkg": {
               "Shared": {
                  "ingress_10_106_32_100_443": {
                        "snat": {
                           "use": "CafeSnatPool"
                        }
                  },
                  "CafeSnatPool": {
                      "class": "SNAT_Pool",
                          "snatAddresses": [
                             "100.128.0.1",
                             "100.128.0.2",
                             "100.128.0.3",
                             "100.128.0.4",
                             "100.128.0.5" 
                      ]
                  }
               }
            }
      }
   }

