apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cafe
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - vmware-system-restricted

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cafe
roleRef:
  kind: Role
  name: cafe
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default



