apiVersion: run.tanzu.vmware.com/v1alpha1      
kind: TanzuKubernetesCluster                  
metadata:
  name: tkg2
  namespace: tkg2
spec:
  distribution:
    version: v1.18.15+vmware.1-tkg.1.600e412
  settings:
    network:
      cni:
        name: calico
      pods:
        cidrBlocks:
        - 100.96.0.0/11
      serviceDomain: tkg1.tkg.bd.f5.com
      services:
        cidrBlocks:
        - 100.64.0.0/13
  topology:
    controlPlane:
      count: 1                           
      class: best-effort-medium           
      storageClass: vsan-default-storage-policy
    workers:
      count: 2
      class: best-effort-medium                
      storageClass: vsan-default-storage-policy

